---
version: "3"
services:

  xray:
    image: haproxytechblog/haproxy-xray
    build:
      context: ./haproxy-xray
      dockerfile: Dockerfile
    volumes:
    - "./haproxy-xray/credentials:/root/.aws/credentials"
    - "./haproxy-xray/cfg.yaml:/etc/amazon/xray/cfg.yaml"

  server:
    image: jmalloc/echo-server
    environment:
    - "PORT=80"

  haproxy:
    image: haproxytech/haproxy-ubuntu:1.9.8
    volumes:
    - "./haproxy/haproxy.cfg:/etc/haproxy/haproxy.cfg"
    ports:
    - "8080:80"
    - "8404:8404"
    depends_on:
    - xray
    - server